# Generated by Django 4.1.1 on 2022-10-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contributionID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.CharField(max_length=20)),
                ('projectID', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectID', models.AutoField(primary_key=True, serialize=False)),
                ('creatorId', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.CharField(max_length=1000)),
                ('targetPrice', models.IntegerField()),
                ('isFeatured', models.BooleanField()),
                ('total', models.IntegerField()),
                ('donateCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
    ]
