# Generated by Django 4.1.1 on 2022-11-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='creationTime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='projects',
            name='creationTime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='creationTime',
            field=models.CharField(default='', max_length=20),
        ),
    ]
