# Generated by Django 4.1.1 on 2022-11-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_contribution_creationtime_projects_creationtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='backgroud',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='users',
            name='facebook',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
