# Generated by Django 4.1.1 on 2022-11-21 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_users_backgroud_users_facebook_users_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='creationTime',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='creationTime',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='total',
            new_name='currentPrice',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='projectID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='image',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='backgroud',
            new_name='coverBackground',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='creationTime',
            new_name='createAt',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='userID',
            new_name='id',
        ),
    ]
