# Generated by Django 4.1.1 on 2022-11-26 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_creationtime_contribution_createat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='projects',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
