# Generated by Django 4.1.1 on 2022-12-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_contribution_createat_alter_projects_createat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='projectID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='userID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='creatorId',
            field=models.IntegerField(),
        ),
    ]
