# Generated by Django 4.1.1 on 2022-12-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_donatecount_projects_donationcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='donationcount',
            new_name='donationCount',
        ),
    ]
