# Generated by Django 4.1.1 on 2022-12-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_donationcount_projects_donationcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='currentPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='donationCount',
            field=models.IntegerField(default=0),
        ),
    ]
