# Generated by Django 4.1.1 on 2022-12-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_projects_currentprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='imageName',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
