# Generated by Django 4.1.1 on 2022-12-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_projects_imagename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='imageName',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
