# Generated by Django 4.1.1 on 2022-12-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_projects_description_alter_projects_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='contributionID',
            new_name='contributionId',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='projectID',
            new_name='projectId',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='userID',
            new_name='userId',
        ),
    ]
