# Generated by Django 4.1.1 on 2022-12-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_contributionid_contribution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='targetPrice',
            field=models.TextField(),
        ),
    ]
